version: '3.9'

services:

  traefik:
    image: traefik:2.10
    command:
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.http.acme.httpchallenge=true"
      - "--certificatesresolvers.http.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.http.acme.email=tu_correo@gmail.com"
      - "--certificatesresolvers.http.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "acme:/acme.json"
    deploy:
      labels:
        - "traefik.enable=true"
    networks:
      - traefik-public

  traefik_estefany:
    image: ghcr.io/tefy89/traefik_estefany:1.0.0
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik_estefany.rule=Host(`traefik_estefany.byronrm.com`)"
        - "traefik.http.routers.traefik_estefany.entrypoints=http"
        - "traefik.http.routers.traefik_estefany-secure.rule=Host(`traefik_estefany.byronrm.com`)"
        - "traefik.http.routers.traefik_estefany-secure.entrypoints=https"
        - "traefik.http.routers.traefik_estefany-secure.tls=true"
        - "traefik.http.routers.traefik_estefany-secure.tls.certresolver=http"
        - "traefik.http.services.traefik_estefany.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

volumes:
  acme:

networks:
  traefik-public:
    external: true
