version: '3.9'

services:

  traefik_estefany:
    image: ghcr.io/tefy89/traefik_estefany:1.0.0
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik_estefany.rule=Host(`traefik_estefany.byronrm.com`)"
        - "traefik.http.routers.traefik_estefany.entrypoints=http"
        - "traefik.http.routers.traefik_estefany-secure.rule=Host(`traefik_estefany.byronrm.com`)"
        - "traefik.http.routers.traefik_estefany-secure.entrypoints=https"
        - "traefik.http.routers.traefik_estefany-secure.tls=true"
        - "traefik.http.routers.traefik_estefany-secure.tls.certresolver=http"
        - "traefik.http.services.traefik_estefany.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
