name: Deploy traefik-estefany

on:
  push:
    branches: "master"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: 🔐 Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB-TOKEN }}

    - name: 🏗️ Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/tefy89/traefik-estefany:1.0.0

    - name: 🧪 Test SSH connection
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS-HOST }}
        username: ${{ secrets.VPS-USER }}
        password: ${{ secrets.VPS-PASSWORD }}
        port: ${{ secrets.VPS-SSH-PORT }}
        script: |
          echo "SSH OK en traefik-estefany"
          hostname
          whoami

    - name: 📤 Enviar stack.yml al servidor
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS-HOST }}
        username: ${{ secrets.VPS-USER }}
        password: ${{ secrets.VPS-PASSWORD }}
        port: ${{ secrets.VPS-SSH-PORT }}
        source: "stack.yml"
        target: "/home/${{ secrets.VPS-USER }}/despliegue"

    - name: 🚀 Despliegue de servicios
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS-HOST }}
        username: ${{ secrets.VPS-USER }}
        password: ${{ secrets.VPS-PASSWORD }}
        port: ${{ secrets.VPS-SSH-PORT }}
        script: |
          echo "📂 Moviéndome al directorio de despliegue"
          cd /home/${{ secrets.VPS-USER }}/despliegue

          echo "🗑️ Eliminando stack previo (si existe)"
          docker stack rm traefik-estefany || true
          sleep 5

          echo "🚀 Desplegando nuevo stack"
          docker stack deploy -c stack.yml --with-registry-auth traefik-estefany

          echo "✅ Despliegue completado con éxito"
