name: Deploy traefik_estefany

on:
  push:
    branches: "master"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: 🔐 Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name:  Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/tefy89/traefik_estefany:1.0.0

    - name: 🧪 Test SSH connection
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "SSH OK en traefik_estefany"

    - name: 📤 Enviar stack.yml al servidor
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        source: "stack.yml"
        target: "/home/${{ secrets.VPS_USER }}/despliegue"

    - name: 🚀 Despliegue de servicios
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          docker stack rm traefik_estefany || true
          docker stack deploy -c stack.yml --with-registry-auth traefik_estefany
